### ISSUE TITLE
`return` missing?

### ISSUE THREAD

**Issue by breadoliveoilsalt** [learn-co-curriculum/recursion-readme#2]
Hi.  Throughout the lab where sumUpTo is defined (or is in the process of being defined), I think at the point of recurssion, where sumUpTo is called again, a `return` is missing.  So, for example, this...

```
function sumUpTo(n){
  if(n > 1){
      sumUpTo(n - 1) + n
  } else {
    return 1
  }
}
```

...would be this instead:

```
function sumUpTo(n){
  if(n > 1){
     return sumUpTo(n - 1) + n
  } else {
    return 1
  }
}
```

[Only change is adding `return` on the third line.]  Without this `return`, the code does not work in console, and all the functions in the next lesson use `return` when making the recursion call.  

Hope that helps.  Please let me know if you think I'm wrong.  Thanks!

**Comment by rrcobb** [comment]
Addressed in #1
